<?php

namespace ValBundle\Entity;

use ValBundle\Entity\AppEntityRepository;

/**
 * RegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegisterRepository extends AppEntityRepository
{
}
